# Numpy Excercises - Part 1 (required)

Naming convention for Jupyter Notebook file :
- WeekNumber_StudentID_StudentName_ExcerciseTitle
- For example : 01_C2022020091_BornPheakdey_Numpy_Excersie

Submit to : https://forms.gle/vFY7ziZ7mKiNERhF9

### 0. Create a Numpy array

In [ ]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

### 1. Show your Numpy version

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


### 2. Given 2 array below, check to see if these 2 array contain zero

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 0])
print(np.all(a))
print(np.all(b))

True
False


### 3. Write a function to test if an array contains NaN

In [ ]:
def find_Nan(array):
  if (np.isnan(array).any()):
    return "Array contain Nan value"
  else:
    return "Array doesn't contain Nan value"

array = [3, 1, 6, 4, 8, np.NaN, 4]
find_Nan(array)

'Array contain Nan value'

### 4. Write a function to check if 2 array are equal. The function should return True if they are equal and False if they are not

In [ ]:
def equal_array(arr1, arr2, l_a1, l_a2):
	if (l_a1 != l_a2):
		return False

	arr1.sort()
	arr2.sort()
 
	for i in range(l_a1):
		if (arr1[i] != arr2[i]):
			return False
	return True

arr1 = [3,6,2,4,1,0,7,9]
arr2 = [4,9,0,7,1,6,2,3]
l_a1 = len(arr1)
l_a2 = len(arr2)

if (equal_array(arr1, arr2, l_a1, l_a2)):
  print("Array are equal")
else:
  print("Array are not equal")



Array are equal


### 5. Create array of 3 zeros, 3 ones, 3 fours. (There should be 3 different array)

In [ ]:
a1 = np.zeros(3)
print(a1)

a2 = np.ones(3)
print(a2)

a3 = np.array([4,4,4], dtype= float)
print(a3)

[0. 0. 0.]
[1. 1. 1.]
[4. 4. 4.]


### 6. Creat 2D array of size 3x4

In [ ]:
array = np.array([[1,2,3,4],
                  [4,5,6,7],
                  [7,8,9,10]])
print(array.shape)

(3, 4)


### 7. Write a function that compute sum of all elements in an array. Note : the array can be any dimension.

In [ ]:
def sum_element(array):
  result = np.sum(array)
  return result

array = np.array([[1,2,3],
                  [2,3,4],
                  [3,4,5]])
sum_element(array)

27

### 8. Call the function in question #7 with 1D array, 2D array and 3D array. Note : you have to call the function 3 times

In [ ]:
# 1D array
array = np.arange(12)
print(array)
sum_element(array)

# 2D array
array.shape = (2,6)
print(array)
sum_element(array)

# 3D array
array.shape = (3,4)
sum_element(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


66

### 9. Write a function 

In [ ]:
def my_Function():
  a = 2
  b = 3
  c = a*b 
  return c

my_Function()

6

### 10. Create a 2D array with shape 3x4 of random numbers

In [ ]:
import numpy.matlib as ml
array_2D = np.array(ml.rand(3,4)) 
print(array_2D)

[[0.00542102 0.62939635 0.1152519  0.47089241]
 [0.45307572 0.47951856 0.7887186  0.61206529]
 [0.57753394 0.76959676 0.63412846 0.14456484]]


### 11. Ceate a function to extract all numbers from a given array which are greater than a specified number. (function header is given below)

In [ ]:
def extract_from_array(array, number):
    for i in array:
      if i > number:
        print(i)

array = np.array([1,2,3,4,5,6,7])
number = 5
extract_from_array(array, number)

6
7


### 12. Write a function to swap rows and columns of a given array

In [ ]:
def swap_R_C(array):
  new_array = np.transpose(array)
  return new_array


array = np.array([[1,1,1],
         [2,2,2],
         [3,3,3]])
swap_R_C(array)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### 13. Compute the mean, standard deviation, and variance of a given array 

In [ ]:
array = np.array([1,2,3,4,5])
mean_val = np.mean(array)
print(mean_val)

standard_deviation = np.std(array)
print(standard_deviation)

variance_val = np.var(array)
print(variance_val)

3.0
1.4142135623730951
2.0


### 14. Ceate a function to flatten and calculate the medain of an array. Note : you can not use the built-in "numpy.median" function. Flatten means convert multi-deminsion array to 1 dimenstion array.

In [ ]:
def function(array):
  # Flatten the array
  array = array.flatten()
  # calculate the median of the array , => To find median, we have to sort the array first
  array = np.sort(array)

  if len(array) % 2 == 0:
    m1 = array[len(array)//2]
    m2 = array[len(array)//2 - 1]
    median = (m1+m2) / 2
  else:
    median = array[len(array)//2]

  return ("Median of array is: ",median)


array = np.array([[1,3,2],
                  [4,6,5],
                  [7,9,8]])
function(array)


('Median of array is: ', 5)

# Numpy Excercises - Part 2 (optional with bonus)

### 15. Ceate a function to count the number of occurrences of each value in a given array of non-negative integers. The function must return a dictionary of key as the values and value as the number of occurrences.

> Indented block



In [ ]:

def find_occurr(array):
  # create empty dictionary 
  dic = {}
  for i in array:
    dic[i] = array.count(i)
  for key, value in dic.items():
    print ("% d : % d"%(key, value))

array = [2,1,3,1,4,2,5,1,6,7,4,5]
find_occurr(array)

 2 :  2
 1 :  3
 3 :  1
 4 :  2
 5 :  2
 6 :  1
 7 :  1
